name: Build & Release

on:
  push:
  pull_request:

jobs:
  agent:

    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) && github.actor != 'mergify[bot]'
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.5
        with:
          graalvm-version: "20.1.0"
          java-version: "java11"
          native-image: "true"
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Cache ivy2
        uses: actions/cache@v2
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}
          restore-keys: |
            ${{ runner.os }}-ivy2-
            ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}

      - name: scala build
        run: |
          sbt -Dsbt.coursier.home=~/.sbt/coursier/ '; project agent; graalvm-native-image:packageBin' -J-Xms3G -J-Xmx6G -J-Xss4m
      - name: docker login
        run: docker login -u janstenpickle -p '${{secrets.DOCKERHUB}}'
      - name: docker build
        shell: bash
        run: |
          export VERSION=`sbt --error 'print version' | tail -n 1 |  sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`

          pushd modules/agent/src/main/docker
          sh build.sh

          docker tag janstenpickle/trace4cats-agent:$GITHUB_RUN_NUMBER janstenpickle/trace4cats-agent:latest
          docker push janstenpickle/trace4cats-agent:$GITHUB_RUN_NUMBER
          docker push janstenpickle/trace4cats-agent:latest

          if echo $VERSION | grep '+'; then
            exit 0
          else
            docker tag janstenpickle/trace4cats-agent:$GITHUB_RUN_NUMBER janstenpickle/trace4cats-agent:$VERSION
            docker push janstenpickle/trace4cats-agent:$VERSION
          fi

          popd

  agent-kafka:

    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) && github.actor != 'mergify[bot]'
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.5
        with:
          graalvm-version: "20.1.0"
          java-version: "java11"
          native-image: "true"
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Cache ivy2
        uses: actions/cache@v2
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}
          restore-keys: |
            ${{ runner.os }}-ivy2-
            ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}

      - name: scala build
        run: |
          sbt -Dsbt.coursier.home=~/.sbt/coursier/ '; project agent-kafka; graalvm-native-image:packageBin' -J-Xms3G -J-Xmx6G -J-Xss4m
      - name: docker login
        run: docker login -u janstenpickle -p '${{secrets.DOCKERHUB}}'
      - name: docker build
        shell: bash
        run: |
          export VERSION=`sbt --error 'print version' | tail -n 1 |  sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`

          pushd modules/agent-kafka/src/main/docker
          sh build.sh

          docker tag janstenpickle/trace4cats-agent-kafka:$GITHUB_RUN_NUMBER janstenpickle/trace4cats-agent-kafka:latest
          docker push janstenpickle/trace4cats-agent-kafka:$GITHUB_RUN_NUMBER
          docker push janstenpickle/trace4cats-agent-kafka:latest

          if echo $VERSION | grep '+'; then
            exit 0
          else
            docker tag janstenpickle/trace4cats-agent-kafka:$GITHUB_RUN_NUMBER janstenpickle/trace4cats-agent-kafka:$VERSION
            docker push janstenpickle/trace4cats-agent-kafka:$VERSION
          fi

          popd

  collector-lite:

    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) && github.actor != 'mergify[bot]'
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.5
        with:
          graalvm-version: "20.1.0"
          java-version: "java11"
          native-image: "true"
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Cache ivy2
        uses: actions/cache@v2
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}
          restore-keys: |
            ${{ runner.os }}-ivy2-
            ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}

      - name: scala build
        run: |
          sbt -Dsbt.coursier.home=~/.sbt/coursier/ '; project collector-lite; graalvm-native-image:packageBin' -J-Xms3G -J-Xmx6G -J-Xss4m
      - name: docker login
        run: docker login -u janstenpickle -p '${{secrets.DOCKERHUB}}'
      - name: docker build
        shell: bash
        run: |
          export VERSION=`sbt --error 'print version' | tail -n 1 |  sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`

          pushd modules/collector-lite/src/main/docker
          sh build.sh

          docker tag janstenpickle/trace4cats-collector-lite:$GITHUB_RUN_NUMBER janstenpickle/trace4cats-collector-lite:latest
          docker push janstenpickle/trace4cats-collector-lite:$GITHUB_RUN_NUMBER
          docker push janstenpickle/trace4cats-collector-lite:latest

          if echo $VERSION | grep '+'; then
            exit 0
          else
            docker tag janstenpickle/trace4cats-collector-lite:$GITHUB_RUN_NUMBER janstenpickle/trace4cats-collector-lite:$VERSION
            docker push janstenpickle/trace4cats-collector-lite:$VERSION
          fi

          popd

  collector:

    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) && github.actor != 'mergify[bot]'
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Cache ivy2
        uses: actions/cache@v2
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}
          restore-keys: |
            ${{ runner.os }}-ivy2-
            ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}

      - name: scala build
        shell: bash
        run: |
          sbt -Dsbt.coursier.home=~/.sbt/coursier/ "; project collector; set ThisBuild / version := \"latest\"; docker:publishLocal" -J-Xms3G -J-Xmx6G -J-Xss4m
      - name: docker login
        run: docker login -u janstenpickle -p '${{secrets.DOCKERHUB}}'
      - name: docker build
        shell: bash
        run: |
          export VERSION=`sbt --error 'print version' | tail -n 1 |  sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`

          docker tag janstenpickle/trace4cats-collector:latest janstenpickle/trace4cats-collector:$GITHUB_RUN_NUMBER
          docker push janstenpickle/trace4cats-collector:$GITHUB_RUN_NUMBER
          docker push janstenpickle/trace4cats-collector:latest

          if echo $VERSION | grep '+'; then
            exit 0
          else
            docker tag janstenpickle/trace4cats-collector:latest janstenpickle/trace4cats-collector:$VERSION
            docker push janstenpickle/trace4cats-collector:$VERSION
          fi

  test:

    runs-on: ubuntu-latest


    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache ivy2
        uses: actions/cache@v2
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}
          restore-keys: |
            ${{ runner.os }}-ivy2-
            ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}
            ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/project/plugins.sbt') }}

      - name: scala build
        run: |
          sbt -Dsbt.coursier.home=~/.sbt/coursier/ '; scalafmtCheckAll; scalafmtSbtCheck; compile; test' -J-Xms3G -J-Xmx6G -J-Xss4m
